owner: PSLmodels
title: OG-USA
branch: master
repo_url: https://github.com/PSLmodels/OG-USA
env:
  BUILD_NUM: 1
sim_time_limit: 20000
resources:
  requests:
    cpu: "2"
    memory: "8G"
  limits:
    cpu: "4"
    memory: "13G"
