owner: PSLmodels
title: OG-USA
branch: memory
# This will install Rick's memory management branch
repo_url: https://github.com/hdoupe/OG-USA
env:
  BUILD_NUM: 2
sim_time_limit: 20000
resources:
  requests:
    cpu: "4"
    memory: "20G"
  limits:
    cpu: "7"
    memory: "28G"
