owner: PSLmodels
title: Tax-Cruncher
branch: master
repo_url: https://github.com/PSLmodels/Tax-Cruncher
env:
  BUILD_NUM: 19
sim_time_limit: 100
resources:
  limits:
    cpu: "2.5"
    memory: "7.5G"
