name: Build

on:
  pull_request:
    branches:
      - master
    paths:
      - "config/**"

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}

  PROJECT: ${{ secrets.PROJECT }}
  CS_URL: ${{ secrets.CS_URL }}
  CS_API_TOKEN: ${{ secrets.CS_API_TOKEN }}

  TAG: ${{ github.sha }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Test, Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: git fetch origin master --depth 2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "git+https://github.com/compute-tooling/compute-studio.git@cluster-refactor#egg=cs-workers&subdirectory=workers"

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "270.0.0"
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GKE_KEY }}

      # Build Docker images
      - name: Build
        run: |
          csw models build

      # Test Docker images
      - name: Test
        if: "!contains(github.event.head_commit.message, 'skip test')"
        run: |
          csw models test

      # Push Docker images to CR
      - name: Push
        run: |
          csw models push
