name: Build

on:
  pull_request:
    branches:
      - master
    paths:
      - "config/**"

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}'

  TAG: latest
  PROJECT: compute-tooling/compute-studio-publish

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Test, Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: git fetch origin master --depth 2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "git+https://github.com/compute-tooling/compute-studio.git@cluster-refactor#egg=cs-workers&subdirectory=workers"

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u hdoupe --password-stdin

      # Build Docker images
      - name: Build
        run: |
          csw models --cr 'docker.pkg.github.com' build

      # Test Docker images
      - name: Test
        if: "!contains(github.event.head_commit.message, 'skip test')"
        run: |
          csw models --cr 'docker.pkg.github.com' test

      # Push Docker images to GitHub container registry
      - name: Push
        run: |
          csw models --cr 'docker.pkg.github.com' push
